In [1]:
import numpy as np

## What is the advantage of numpy over the list?

* consumes less memory.
* fast as compared to the python List (30 times faster)
*  It has better support for mathematical operations.

In [2]:
import time
lst1=list(range(1000000))
lst2=list(range(2000000,3000000))
##
print(len(lst1),len(lst2))

1000000 1000000


In [3]:
lst1[0:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
lst2[0:10]

[2000000,
 2000001,
 2000002,
 2000003,
 2000004,
 2000005,
 2000006,
 2000007,
 2000008,
 2000009]

In [9]:
sum=0
t1=time.time()   #11:05:20
for a, b in zip(lst1, lst2):
    sum = sum+( a+b)
t2=time.time()  # final time   #11:05:50
print(t2-t1)

0.1998598575592041


In [11]:
import numpy as np

aa=np.asarray(lst1)
bb=np.asarray(lst2)
t1=time.time()
res=np.sum(bb+aa)
t2=time.time()
print(t2-t1)

0.00847768783569336


In [10]:
def sigmoid (a):   #[[1,2,3]]
    return 1/(1+np.exp(-a))


a=np.array([1,2,3])
sigmoid(a)

array([0.73105858, 0.88079708, 0.95257413])

In [18]:
def add10(a):
    return a+10

a=np.array([1,2,3])
add10(a)

array([11, 12, 13])

### Convert Python List to numpy Arrays

In [20]:
ll=[3,4,5]

ll_np=np.asarray(ll)

print(type(ll_np))

ll2d=[[3,4,5],[6,7,8]]

print(len(ll2d))

ll2d_np=np.asarray(ll2d)

print(ll2d_np.shape)



<class 'numpy.ndarray'>
2
(2, 3)


### # convert numpy array to list

In [22]:
arr20=np.array([3,4,5])

print(type(arr20))

lst100=arr20.tolist()

print(type(lst100))

<class 'numpy.ndarray'>
<class 'list'>


In [23]:
arr6D=np.array([10,12],ndmin=2)
print(arr6D)
print(arr6D.ndim)

[[10 12]]
2


## np.random.seed()
Seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator. For the first time when there is no previous value, it uses current system time.

In [15]:
np.random.seed(2)
np.random.randint(low = 1, high = 10, size = 50)

array([9, 9, 7, 3, 9, 8, 3, 2, 6, 5, 5, 6, 8, 4, 7, 5, 4, 8, 7, 2, 4, 6,
       9, 5, 7, 4, 3, 1, 5, 3, 5, 2, 8, 9, 3, 9, 8, 2, 7, 9, 6, 4, 1, 1,
       3, 9, 9, 3, 7, 6])

## numpy.unique
- This function returns an array of unique elements in the input array.
- The function can be able to return a tuple of array of unique vales and an array of associated indices

In [21]:
a = np.array([10,10,1,2,1,3,2,4,6,6,6])
a1=np.unique(a)
print(a1)

[ 1  2  3  4  6 10]


In [26]:
### u, indices= np.unique(a, return_index=True)
u, indices= np.unique(a, return_index=True)
print(u, indices)

[ 1  2  3  4  6 10] [2 3 5 7 8 0]


In [24]:
#####
u, count1= np.unique(a, return_counts=True)
print(u, count1)

[ 1  2  3  4  6 10] [2 2 1 1 3 2]


## Aggregations: Min, Max, and Everything In Between
- sum, min, max, mean, and std

In [25]:
arr=np.arange(2,10).reshape(4,2)
print(arr)

print(np.min(arr))
print(np.max(arr))

print(np.min(arr,axis=0)) # axis 0 = column
print(np.min(arr,axis=1)) # axis 1 = row

[[2 3]
 [4 5]
 [6 7]
 [8 9]]
2
9
[2 3]
[2 4 6 8]


## argmin and argmax
- argmin: Returns the indices of the minimum values along an axis.
- argmax: Returns the indices of the maximum values along an axis.

In [29]:
arr1000=np.array([1,10,-1,2,-30])
print(np.argmin(arr1000,axis=0))
print(np.argmax(arr1000))

#Softmax => probalbilities > index of the highest prob.

4
1


### numpy.argsort()

- Returns the indices that would sort an array.
- Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

In [30]:
# input array
in_arr = np.array([ 2, 0,  1, 5, 4, 1, 9])
print ("Input unsorted array : ", in_arr)

out_arr = np.argsort(in_arr)
print ("Output sorted array indices : ", out_arr)
print("Output sorted array : ", in_arr[out_arr])

Input unsorted array :  [2 0 1 5 4 1 9]
Output sorted array indices :  [1 2 5 0 4 3 6]
Output sorted array :  [0 1 1 2 4 5 9]


In [31]:
## np.argsort in decending order
res=np.argsort(in_arr)[::-1]
print(res) # return indeces
print(in_arr[res])

[6 3 4 0 5 2 1]
[9 5 4 2 1 1 0]


In [ ]:
a = np.arange(6).reshape(2,3) + 10
print(a)

print(np.argmin(a,axis=0))

[[10 11 12]
 [13 14 15]]
[0 0 0]


In [ ]:
a = np.arange(6).reshape(2,3) + 10
print(a)

print(np.argmin(a,axis=1))

[[10 11 12]
 [13 14 15]]
[0 0]


In [ ]:
import numpy as np
A = np.array([1, 7, 9, 2, 0.1, 17, 17, 1.5]).reshape(4,2)
print('A:')
print(A)

A:
[[ 1.   7. ]
 [ 9.   2. ]
 [ 0.1 17. ]
 [17.   1.5]]


In [ ]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("Inverse of A:")
print(A_inv)

Matrix A:
[[1 2]
 [3 4]]
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Normal Distribution
The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.



### split(): Split an array into multiple sub-arrays of equal size

In [ ]:

x = np.arange(10)

np.split(x,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### numpy.where
- Return elements chosen from x or y depending on condition.

In [16]:
arr_rand=np.array([1,2,10,5,100,50])
res = np.where(arr_rand > 5)
print(res)
print(arr_rand[res])

(array([2, 4, 5]),)
[ 10 100  50]


## write a python function two calculate Euclidean distance between two points

In [ ]:
def euclidean_distance(x1,x2):
    return np.sqrt((np.sum(x1-x2)**2))

x1=np.array([2,3,10])
x2=np.array([2,3,4])
euclidean_distance(x1,x2)

6.0